# -----------------
# FRONTEND-SERVICES 
# -----------------
services: 
  mobile: 
    container_name: ${PROJECT_FULL_NAME}_mobile
    build: 
      context: ./frontends
      dockerfile: Dockerfile
      args: 
        NODE_VERSION: ${PROJECT_CTR_NODE_VERSION}
    working_dir: /home/project/source
    environment: 
      PROJECT_RAW_CLI: ${PROJECT_RAW_CLI:-false}
    env_file: 
      - ${PROJECT_ROOT}/setup/vars/.env
      - ${PROJECT_ROOT}/setup/vars/.env.${PROJECT_RUNTIME_MODE}
      - ${PROJECT_ROOT}/setup/vars/.env.final
      - ${DFST_PATH}/.env
    command: sh /home/project/start.sh
    volumes: 
      - ${PROJECT_ROOT}/source/mobile:/home/project/source 
      - ./frontends/start.sh:/home/project/start.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks: 
      main: {}
      dfst-dns-net: 
        aliases: 
          - ${PROJECT_FULL_NAME}_mobile
    dns: 
      - ${DFST_DNS_IP}
      - 1.1.1.1 
      - 8.8.8.8

  web: 
    container_name: ${PROJECT_FULL_NAME}_web
    build: 
      context: ./frontends 
      dockerfile: Dockerfile
      args: 
        NODE_VERSION: ${PROJECT_CTR_NODE_VERSION}
    working_dir: /home/project/source
    command: sh /home/project/start.sh
    env_file: 
      - ${PROJECT_ROOT}/setup/vars/.env
      - ${PROJECT_ROOT}/setup/vars/.env.${PROJECT_RUNTIME_MODE}
      - ${PROJECT_ROOT}/setup/vars/.env.final
      - ${DFST_PATH}/.env
    volumes: 
      - ${PROJECT_ROOT}/source/web:/home/project/source 
      - ./frontends/start.sh:/home/project/start.sh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      PROJECT_RAW_CLI: ${PROJECT_RAW_CLI:-false}
    networks: 
      main: {}
      dfst-dns-net: 
        aliases: 
          - ${PROJECT_FULL_NAME}_web
    dns: 
      - ${DFST_DNS_IP}
      - 1.1.1.1 
      - 8.8.8.8