# ---------------
# LARAVEL BACKEND
# ---------------
services: 
  backend:
    build: 
      args: 
        PHP_FPM_VERSION: ${PROJECT_CTR_PHP_FPM_VERSION}
        COMPOSER_TAG: ${PROJECT_CTR_COMPOSER_TAG}
    volumes: 
      - ./backend/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./backend/clear-config.sh:/home/project/clear-config.sh
      - caddy-data:/data/caddy
    command: |
      sh -c "
        useradd -u $USER_ID www-data &&
        bash /home/project/clear-config.sh &
        php-fpm --nodaemonize 
      "
    user: $USER_ID

# -------
# VOLUMES
# -------
volumes: 
  laravel-storage: 
    driver: local