# ---------------
# LARAVEL BACKEND
# ---------------
services: 
  backend:
    build: 
      args: 
        PHP_FPM_VERSION: ${PROJECT_CTR_PHP_FPM_VERSION}
        COMPOSER_TAG: ${PROJECT_CTR_COMPOSER_TAG}
    volumes: 
      - ./backend/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./backend/clear-config.sh:/home/project/clear-config.sh
      - caddy-data:/data/caddy
      - ./backend/start.sh:/home/project/start.sh
      - psysh-config:/home/project/.config/psysh
    command: sh /home/project/start.sh
    user: $PROJECT_USER

# -------
# VOLUMES
# -------
volumes: 
  laravel-storage: 
    driver: local
  psysh-config: 
    driver: local