#!/bin/bash

set -a 

# Activate environment files.
source setup/vars/.env 
source setup/vars/.env.${PROJECT_RUNTIME_MODE_AS:-${PROJECT_RUNTIME_MODE:-local}}
source setup/vars/.env.versions
source setup/vars/.env.final

# Get path to DFST main folder.
# Stored in DFST{VERSION_NO}_PATH
export DFST_PATH=${DFST_BASE_DIR:-/opt/dfst}/${DFST_VERSION}/main

# Load configuration of DFST.
source $DFST_PATH/.env

# Store path to project.
export PROJECT_PATH=$(pwd)

# Tag Version
export RETAG=${PROJECT_IMAGE_TAG:-$(cat ./setup/values/docker-latest-tag)}
export PROJECT_IMAGE_TAG=${PROJECT_IMAGE_TAG_AS:-$RETAG}

set +a  


